apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: playlist
  labels:
    app: playlist
    release: c756
spec:
  namespaceSelector:
    matchNames:
    - project-services
  selector:
    matchLabels:
      app: playlist
  endpoints:
  - port: http
    path: /metrics
